name: Deploy Plugins

on: [pull_request, push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - uses: actions/checkout@v4.1.5

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      
      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.7
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: yarn tsc:full
        run: yarn tsc:full

      - name: yarn lint
        run: yarn backstage-cli repo lint

      - name: yarn build
        run: yarn backstage-cli repo build --all

      - name: yarn test
        run: yarn test --no-watch

  release:
    needs: test

    if: github.ref == 'refs/heads/master' && github.repository_owner == 'antoinedao'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      CI: 'true'
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - uses: actions/checkout@v4.1.5

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.7
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}
      
      - name: semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192